base:
  host: 192.168.0.243
  port: 7000
  controller: xbox360
  radio:
    name: SX1262
    alwaysUse: False
    usbId: /dev/usb0
drone:
  id: 1
  radio:
    name: SX1262
    alwaysUse: False
    usbId: /dev/usb0
  sensors:
    - name: frienda_obstacle_431S
      config:
        - pins:
            - 1
            - 2
  outputs:
    - name: hawks_work_ESC
      config:
        - pins:
            - 15
            - 16
  controlAlgorithmPriority:
    - obstacle_avoidance
